  $(document).ready(function(){
      $('.partners').slick({
        autoplay:true,
        autoplaySpeed:4000,
        infinite:true,
        variableWidth:true,
        pauseOnHover:true,
        arrows:false,
        slidesToShow:11,
        draggable:false
      });
    });