$(document).ready(function(){
  $('.partners').slick({
    autoplay:true,
    autoplaySpeed:4000,
    infinite:true,
    variableWidth:true,
    pauseOnHover:true,
    arrows:false,
    slidesToShow:11,
    draggable:false
  });
});

$(document).ready(function(){
  $('.clients').slick({
    autoplay:true,
    autoplaySpeed:4000,
    infinite:true,
    variableWidth:true,
    pauseOnHover:true,
    arrows:false,
    slidesToShow:12,
    draggable:false
  });
});

$(document).ready(function(){
  $('.banner').slick({
    autoplay:true,
    autoplaySpeed:5000,
    speed:200,
    infinite:true,
    variableWidth:false,
    pauseOnHover:true,
    arrows:false,
    dots:true,
    slidesToShow:1,
    draggable:false,
    centerMode:true,
    centerPadding:false,
    useCSS:false    
  });
});